### ISSUE TITLE
Include the yarn.lock file in the yarn tgz artifact.

### ISSUE THREAD

**Issue by giovanny-castillo** [JacobsFederal/Collector-Node-Web#3]
Hello! It'd be great if the yarn.lock file was included in the yarn artifact created by the pipeline. Ideally, this should be zipped with the other yarn stuff so that all of the yarn files needed are all in one place.

I copy and pasted a lot of the stuff present in the pipeline already to upload the yarn.lock as a separate file in the no-bom branch but ideally, it would be integrated with the yarn artifact instead.

**Comment by pappasjfed** [comment]
How about just adding those files to existing archives rather than have it as a separate one?
Note that those files are already in the release in the source code downloads.

**Comment by pappasjfed** [comment]
Pulled into main.  

Yarn.lock, package.json, package-lock.json, and .yarnrc.yml are now included in both the archives.  ( #6 )

Split bom off to new branch. ( #5 )
